language: node_js
node_js:
  - '0.10.x'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-angularjs-cordova' ]; then cd .. && eval "mv $currentfolder generator-angularjs-cordova" && cd generator-angularjs-cordova; fi

